server:
  port: 8080

j-atomic-ledger:
  base-dir: ./data/ledger-demo # 数据存储路径
  engine-name: wallet-core     # 引擎名称
  queue-size: 1024             # 异步落库队列
  snapshot-interval: 50000     # 每1万条做一次快照
  idempotency: GUAVA           # 使用布隆过滤器去重